//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlista
    {
        public Playlista()
        {
            this.Prijenosicas = new HashSet<Prijenosica>();
        }
    
        public int Idplaylista { get; set; }
    
        public virtual ICollection<Prijenosica> Prijenosicas { get; set; }
    }
}
