//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SM.Store.Api.Models
{
    public partial class ProductCM
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; } 
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<DateTime> AvailableSince { get; set; }      
    }
    
}
