//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijenosica
    {
        public int PrijenosnicaId { get; set; }
        public int Id { get; set; }
        public int Broj { get; set; }
    
        public virtual TablicaHitova TablicaHitova { get; set; }
    }
}
