
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sonar.Web.Model
{

using System;
    using System.Collections.Generic;
    
public partial class EventSubscription
{

    public int Id { get; set; }

    public int PersonID { get; set; }

    public int EventTypeID { get; set; }

    public int TownID { get; set; }



    public virtual EventType EventType { get; set; }

    public virtual Person Person { get; set; }

    public virtual Town Town { get; set; }

}

}
