

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sonar.Web.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class hackathon_shift_2016_testEntities : DbContext
{
    public hackathon_shift_2016_testEntities()
        : base("name=hackathon_shift_2016_testEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Comment> Comment { get; set; }

    public virtual DbSet<Event> Event { get; set; }

    public virtual DbSet<EventPerson> EventPerson { get; set; }

    public virtual DbSet<EventState> EventState { get; set; }

    public virtual DbSet<EventSubscription> EventSubscription { get; set; }

    public virtual DbSet<EventType> EventType { get; set; }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<PersonSubscription> PersonSubscription { get; set; }

    public virtual DbSet<PersonType> PersonType { get; set; }

    public virtual DbSet<SotialNetwork> SotialNetwork { get; set; }

    public virtual DbSet<Town> Town { get; set; }

}

}

