# -*- coding: utf-8 -*-
# Deployment settings for autoskola5.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.6/s3e/makefile_builder/mkb.py', 'c:/Users/Ante/Desktop/IOS_App/autoskola5/autoskola5.mkb', '--buildenv=VC12X', '--fake-vc-call', '--deploy-only']
mkb = 'c:/Users/Ante/Desktop/IOS_App/autoskola5/autoskola5.mkb'
mkf = ['c:\\marmalade\\7.6\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.6\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\zlib\\zlib.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Ante/Desktop/IOS_App/autoskola5\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'autoskola5'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'autoskola5'
    long_caption = 'autoskola5'
    version = [0, 0, 1]
    config = ['c:/Users/Ante/Desktop/IOS_App/autoskola5/data/app.icf']
    data_dir = 'c:/Users/Ante/Desktop/IOS_App/autoskola5/data'
    mkb_dir = 'c:/Users/Ante/Desktop/IOS_App/autoskola5'
    iphone_link_lib = []
    osx_ext_dll = []
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws8_extra_res = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    android_ext_target_sdk_version = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    android_ext_min_sdk_version = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    iphone_extra_plist = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_x86/autoskola5.so',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_x86/autoskola5.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_x86_tizen/autoskola5.s86',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_x86_tizen/autoskola5.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_firefoxos/autoskola5.js',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_firefoxos/autoskola5.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_mips/autoskola5.so',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_mips/autoskola5.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_arm/autoskola5.s3e',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_arm/autoskola5.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_mips/autoskola5.so',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_mips/autoskola5.so',
                 },
         'aarch64_gcc' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_aarch64/autoskola5.s3e',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_aarch64/autoskola5.s3e',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_gcc_x86_android/autoskola5.so',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_gcc_x86_android/autoskola5.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_arm/autoskola5.s3e',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_arm/autoskola5.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Debug_autoskola5_VC12X_x86/autoskola5.s86',
                   'release' : r'c:/Users/Ante/Desktop/IOS_App/autoskola5/build_autoskola5_vc12x/Release_autoskola5_VC12X_x86/autoskola5.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
